api/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
@author: alishtory
@site: https://github.com/alishtory/xsadmin
@time: 2017/3/7 21:37
'''

from .views import *
from django.conf.urls import url,include
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse

@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'user_port': reverse('api:user_port', request=request, format=format),
    })

urlpatterns = [
    url(r'^$', api_root),
    url(r'^user_port/$', UserPortView.as_view(), name='user_port'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += [
    url(r'^wechat/$', WeChatView.as_view(), name='wechat'),
]

home/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
@author: alishtory
@site: https://github.com/alishtory/xsadmin
@time: 2017/2/26 16:57
'''
from django.conf.urls import url
from .views import *

app_name = 'home'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^get_gee_captcha/$', GeeCaptchaView.as_view(), name='get_gee_captcha'),
    url(r'^code\.html$', InviteCodeView.as_view(), name='invite_code'),
    url(r'^(?P<slug>[\w-]+)\.html$', PostPageView.as_view(), name= 'post_page'),
    url(r'^(index/)?$', PostPageView.as_view(), name='index'),
]

user/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
@author: alishtory
@site: https://github.com/alishtory/xsadmin
@time: 2017/2/26 18:23
'''

from django.conf.urls import url
from .views import *
from django.views.generic import TemplateView
from django.urls import reverse_lazy

app_name = 'user'

urlpatterns = [
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^(index/|dashboard/)?$', DashboardView.as_view(),name='dashboard'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^personal_profile/$', PersonalProfileView.as_view(), name='personal_profile'),
    url(r'^passwd/$', PasswdView.as_view(), name='passwd'),
    url(r'^checkin/$', CheckInView.as_view(), name='checkin'),
    url(r'^switch_node_group/$', SwitchNodeGroupView.as_view(), name='switch_node_group'),
    url(r'^password/$', PasswordView.as_view(), name='password'),
    url(r'^nodes/(?P<tag_slug>[\w-]+)?$', NodeListView.as_view(), name='nodes'),
    url(r'^node_qr_info/$', NodeQrInfoView.as_view(), name= 'node_qr_info'),
    url(r'^download_cfg/$', DownloadNodeCfgView.as_view(), name='download_cfg'),
    url(r'^post_detail/(?P<pk>\d+)$', PostDetailView.as_view(), name= 'post_detail'),
    url(r'^posts/$', PostListView.as_view(), name='posts'),
]

menus = (
    {'title': '仪表盘', 'title_en': 'Dashboard', 'icon': 'dashboard', 'url_name': 'user:dashboard', 'children': ()},
    {'title': '用户中心', 'title_en': 'User Center','icon': 'user', 'url_name': '', 'children': (
        {'title': '我的信息', 'title_en': 'My Profile', 'icon': 'users', 'url_name': 'user:profile'},
        {'title': '安全设置', 'title_en': 'Safe Setting', 'icon': 'user-secret', 'url_name': 'user:password'},
        {'title': '连接设置', 'title_en': 'Connection Setting', 'icon': 'connectdevelop', 'url_name': 'user:passwd'},
        {'title': '用户属性', 'title_en': 'Personal Profile', 'icon': 'user-md', 'url_name': 'user:personal_profile'},
    )},
   {'title': '每日签到', 'title_en': 'Check In', 'icon': 'flag-checkered', 'url_name': 'user:checkin', 'children': ()},
    {'title': '节点中心', 'title_en': 'Node Center', 'icon': 'codepen', 'url_name': 'user:nodes', 'children': ()},
    {'title': '站内通告', 'title_en': 'Site Notice', 'icon': 'comment', 'url_name': 'user:posts', 'children': (
        {'title': '通告详情', 'title_en': 'Notice Detail', 'icon': 'comment', 'url_name': 'user:post_detail', 'no_reverse': True},
    )},
)

xsadmin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home.views import MyRecover
from django.views.generic import RedirectView
from django.urls import reverse_lazy
admin.autodiscover()
admin.site.login = RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^user/', include('user.urls',namespace='user')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^pwd/recover/$', MyRecover.as_view(), name='password_reset_recover'),
    url(r'^pwd/', include('password_reset.urls')),
    url(r'', include('home.urls',namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
@author: ‘wang_pc‘
@site: 
@software: PyCharm
@file: forms.py
@time: 2017/3/1 16:21
'''
from django import forms
from django.forms import fields
from django.forms import widgets
from django.urls import resolvers
from django.contrib.auth import authenticate
from django.core.validators import EmailValidator,RegexValidator,ValidationError
from user.models import User,InviteCode
import datetime

username_regex = r'^\w+$'

class LoginForm(forms.Form):
    password = fields.CharField(required=True,max_length=64,min_length=8,
        widget= widgets.PasswordInput(attrs={'class': 'form-control','placeholder': '登录密码'}))
    userfield = fields.CharField(required=True,max_length=64,
        widget= widgets.TextInput(attrs={'class': 'form-control','placeholder': '用户名/邮箱'}))
    remember = fields.BooleanField(required=False, initial= {'default': True })

    def clean_userfield(self):
        userfield = self.cleaned_data.get('userfield')
        if '@' in userfield:
            EmailValidator()(userfield)
        else:
            RegexValidator(regex= username_regex, message='用户名不合法')(userfield)
        return userfield

    error_messages = {
        'invalid_login': '用户 %(username)s 不存在或密码错误',
        'inactive':'用户 %(username)s 未激活',
    }

    def clean(self):
        userfield = self.cleaned_data.get('userfield')
        password = self.cleaned_data.get('password')
        if userfield is not None and password is not None:
            self.user_cache = authenticate(user_auth_field=userfield, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': userfield},
                )
            elif not self.user_cache.is_active:
                raise forms.ValidationError(
                    self.error_messages['inactive'],
                    code='inactive',
                    params={'username': userfield},
                )
        return self.cleaned_data

class RegisterForm(forms.Form):
    username = fields.CharField(required=True, max_length=64, min_length=4,
            widget= widgets.TextInput(attrs={'class': 'form-control','placeholder': '用户名'}))
    email = fields.EmailField(required=True, max_length=128, min_length= 6,
            widget= widgets.EmailInput(attrs={'class': 'form-control','placeholder': '邮箱'}))
    password = fields.CharField(required=True, max_length= 128, min_length= 8,
        widget= widgets.PasswordInput(attrs={'class': 'form-control','placeholder': '登录密码'}))
    password2 = fields.CharField(required=True, max_length= 128, min_length= 8,
        widget= widgets.PasswordInput(attrs={'class': 'form-control','placeholder': '确认密码'}))
    invite_code = fields.CharField(required=True,max_length=64,min_length=8,
        widget= widgets.TextInput(attrs={'class': 'form-control','placeholder': '邀请码'}))

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password == password2:
            return password2
        else:
            raise forms.ValidationError(message='确认密码不正确')

    def clean_invite_code(self):
        invite_code = self.cleaned_data.get('invite_code')
        try:
            code = InviteCode.objects.get(code__exact=invite_code)
            if code.enable:
                return invite_code
            else:
                raise forms.ValidationError(message='邀请码已被使用')
        except InviteCode.DoesNotExist or InviteCode.MultipleObjectsReturned:
            raise forms.ValidationError(message='邀请码不存在')

home/views.py
from django.shortcuts import render
from django.views.generic import *
from django.contrib.auth import login,logout as auth_logout
from django.contrib.auth.views import _get_login_redirect_url
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from .forms import *
from django.conf import settings
from django.utils import timezone
from datetime import timedelta
from . import utils
from django.http import HttpResponse,HttpResponseForbidden
from geetest import GeetestLib
from django.core.exceptions import PermissionDenied
from user import utils as UserUtils
from user.models import Post
from django.http.response import Http404
from django.db.models import Q
from password_reset.views import Recover

# Create your views here.

REDIRECT_FIELD_NAME = 'next'

class AuthedRedirectMixin(object):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == request.path:
                raise ValueError('LOGIN_REDIRECT_URL配置错误，不能指向login的URL，否则会无限重定向')
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)


class GeeCaptchaValidateMixin(object):

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            gt = GeetestLib(settings.GEE_CAPTCHA_ID, settings.GEE_PRIVATE_KEY)
            challenge = request.POST.get(gt.FN_CHALLENGE, '')
            validate = request.POST.get(gt.FN_VALIDATE, '')
            seccode = request.POST.get(gt.FN_SECCODE, '')
            status = request.session.get(gt.GT_STATUS_SESSION_KEY)
            user_id = request.session.get("gee_user_id")
            if status:
                result = gt.success_validate(challenge, validate, seccode, user_id)
            else:
                result = gt.failback_validate(challenge, validate, seccode)
            if not result:
                raise PermissionDenied('请正确滑动解锁')
        return super().dispatch(request, *args, **kwargs)



class LoginView(AuthedRedirectMixin, GeeCaptchaValidateMixin, FormView):

    template_name = 'home/login.html'
    form_class = LoginForm

    def get_success_url(self):
        request = self.request
        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME, ''))
        redirect_to = _get_login_redirect_url(request,redirect_to)
        return redirect_to

    def form_valid(self, form):
        user = form.user_cache
        login(self.request, user)
        user.this_login_date = timezone.now()
        user.this_login_ip = utils.get_remote_ip(self.request)
        user.save()
        if not form.cleaned_data.get('remember'):
            self.request.session.set_expiry(0)
        return super(LoginView,self).form_valid(form)


class RegisterView(AuthedRedirectMixin, GeeCaptchaValidateMixin, FormView):

    form_class = RegisterForm
    template_name = 'home/register.html'

    def get_initial(self):
        inital = super().get_initial()
        inital['invite_code'] = self.request.GET.get('invite_code','')
        return inital

    def get_success_url(self):
        return settings.LOGIN_REDIRECT_URL

    def form_valid(self, form):
        #验证无误，注册用户，废除邀请码
        code = InviteCode.objects.get(code__exact=form.cleaned_data.get('invite_code'))
        ip = utils.get_remote_ip(self.request)
        now = timezone.now()
        extra_fields = {
            'transfer_enable': code.traffic,
            'reg_ip': ip,
            'last_login_ip': ip,
            'this_login_ip': ip,
        }
        user = User.objects.create_user(username= form.cleaned_data['username'],
                email= form.cleaned_data['email'],password= form.cleaned_data['password'], **extra_fields)

        code.enable = False
        code.used_user = user
        code.used_time = now
        code.save()
        login(request=self.request,user=user)
        return super(RegisterView,self).form_valid(form)


class GeeCaptchaView(View):

    def post(self, request, *args, **kwargs):
        gee_user_id = request.session.get('gee_user_id')
        if gee_user_id is None:
            gee_user_id = UserUtils.gen_api_key()
            request.session["gee_user_id"] = gee_user_id
        gt = GeetestLib(settings.GEE_CAPTCHA_ID, settings.GEE_PRIVATE_KEY)
        status = gt.pre_process(gee_user_id)
        request.session[gt.GT_STATUS_SESSION_KEY] = status

        response_str = gt.get_response_str()
        return HttpResponse(response_str, content_type='application/json')

class InviteCodeView(TemplateView):
    template_name = 'home/code.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        delay = timedelta(minutes=10)
        context['codes'] = InviteCode.objects.filter(
            (Q(type=InviteCode.TYPE_DEFAULT)|
             (Q(type=InviteCode.TYPE_TIMING)&Q(show_time__gte=now))
             )&(Q(enable=True)|Q(used_time=None)|Q(used_time__range=(now-delay,now+delay)))).order_by('-enable','-id')[:30]
        return context

class PostPageView(TemplateView):

    page_temp_list = ('index', 'about', 'download', 'tos')
    page = None
    default_slug = 'index'
    current_slug = default_slug

    def get_template_names(self):
        if self.page is None:
            if self.current_slug in self.page_temp_list:
                return 'home/%s.html' % self.current_slug
            else:
                raise Http404('No That Page!')
        else:
            return 'home/post_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.current_slug = self.kwargs.get('slug', self.default_slug)
        try:
            page = Post.objects.get(slug__iexact= self.current_slug, content_type= 'PAGE', status= 'PUBLISHED')
            self.page = page
            context['page'] = page
        except Post.DoesNotExist or Post.MultipleObjectsReturned:
            pass
        return context

class MyRecover(GeeCaptchaValidateMixin, Recover):

    pass

templates/home/about.html
{% extends './layout.html' %}
{% block title %}关于我们{% endblock %}
 
{% block content %}
<div class="col-lg-10 col-lg-offset-1 col-md-12">
<h2 class="page-header">About <small>关于我们</small></h2>
<p>We are a group of people who love freedom, we want to be able to open the door and see the outside world!</p>
<p>
Thanks for Shadowsocks team very much, enable to develop such a good application.
</p>
<p>
    This site provides services Shadowsocks account service, not Shadowsocks official website, please know it.
</p>
</div>
{% endblock %}

templates/home/analytics.html
<!-- 统计分析代码 -->

templates/home/faq.html
{% extends './layout.html' %}
{% block title %}常见问题{% endblock %}
 
{% block content %}

常见问题页面
{% endblock %}

templates/home/footer.html
<footer id="main-footer">
    <div class="container">
        <div class="copyright">© 2016-<span itemprop="copyrightYear">{% now 'Y' %}</span>
        　<i class="fa fa-coffee"></i>　由 <a href="{{ PROJECT_URL }}" target="_blank">{{ PROJECT_NAME }}</a> 强力驱动
        </div>
    </div>
</footer>

templates/home/header.html
<!-- header -->{% load static %}
<header id="header" class="clearfix">
    <!-- navbar -->
    <nav class="navbar navbar-default">
        <div class="container">
            <!-- navbar-header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">折叠导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:index' %}"><img class="img-logo" src="{% static 'images/logo.png' %}" alt="Logo"><span class="site-title">{{ SITE_NAME }}</span></a>
            </div>
            <!-- /navbar-header -->

            <div class="navbar-left">
                <div class="collapse navbar-collapse" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        {% url 'home:index' as inde_url %}
                        {% url 'home:invite_code' as invite_code_url %}
                        {% url 'home:post_page' slug='download' as download_url %}
                        {% url 'home:post_page' slug='about' as about_url %}
                        {% url 'home:post_page' slug='faq' as faq_url %}
                        {% url 'home:post_page' slug='tos' as tos_url %}
                        <li {% ifequal request.path inde_url %}class="active"{% endifequal %}>
                            <a href="{{ inde_url }}"><i class="fa fa-home" aria-hidden="true"></i> 主页</a>
                        </li>
                        <li {% ifequal request.path download_url %}class="active"{% endifequal %}>
                            <a href="{{ download_url }}"><i class="fa fa-arrow-circle-down" aria-hidden="true"></i> 下载</a>
                        </li>
                        <li {% ifequal request.path invite_code_url %}class="active"{% endifequal %}>
                            <a href="{{ invite_code_url }}"><i class="fa fa-codiepie" aria-hidden="true"></i> 邀请码</a>
                        </li>
                        <li {% ifequal request.path about_url %}class="active"{% endifequal %}>
                            <a href="{{ about_url }}"><i class="fa fa-flag-checkered" aria-hidden="true"></i> 关于</a>
                        </li>
                        <li {% ifequal request.path tos_url %}class="active"{% endifequal %}>
                            <a href="{{ tos_url }}"><i class="fa fa-book" aria-hidden="true"></i> 服务条款</a>
                        </li>
                    </ul>
                </div>
            </div><!-- navbar-left -->

            <!-- nav-right -->
            <div class="nav-right">
                <ul class="sign-in">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'user:dashboard' %}"><i class="fa fa-dashboard"></i> 仪表盘</a></li>　|
                    <li><a href="{% url 'user:logout' %}"><i class="fa fa-key"></i> 退出</a></li>
                {% else %}
                    <li><i class="fa fa-user-circle-o"></i></li>
                    <li><a href="{% url 'home:register' %}">注册</a></li>　|
                    <li><a href="{% url 'home:login' %}">登录</a></li>
                {% endif %}
                </ul><!-- sign-in -->
            </div>
            <!-- nav-right -->
        </div><!-- container -->
    </nav><!-- navbar -->
</header><!-- header -->

templates/home/login.html
{% extends 'home/layout.html' %}
{% block title %}用户登录{% endblock %}
{% block content %}
<div class="eternity-form container">
    <div class="login-form-section">
        <div class="login-content " data-animation="bounceIn">
            <form method="post">
                <div class="section-title">
                    <h3>登录你的帐号</h3>
                </div>{% csrf_token %}
                <div class="textbox-wrap">
                    <div class="input-group">
                        <span class="input-group-addon "><i class="fa fa-user"></i></span>
                        {{ form.userfield }}
                    </div>
                    {% if form.userfield.errors %}<label class="label-warning val-error">{{ form.userfield.errors.0 }}</label>{% endif %}
                </div>
                <div class="textbox-wrap">
                    <div class="input-group">
                        <span class="input-group-addon "><i class="fa fa-key"></i></span>
                        {{ form.password }}
                    </div>
                    {% if form.password.errors %}<label class="label-warning val-error">{{ form.password.errors.0 }}</label>{% endif %}
                </div>
                <div style="margin: 12px 0px 10px 32px">
                   <div id="embed-captcha"></div>
                    <p id="wait" class="show">正在加载验证码......</p>
                    <p id="notice" class="hide">请先拖动验证码到相应位置</p>
                </div>
                <div class="login-form-action clearfix">
                    <div class="checkbox pull-left">
                        <div class="custom-checkbox">
                            {{ form.remember }}
                        </div>
                        <span class="checkbox-text pull-left">&nbsp;记住登录状态</span>
                    </div>
                    <button type="submit" id="embed-submit" class="btn btn-success pull-right green-btn"> 登录 <i class="fa fa-sign-in"></i></button>
                </div>
                {% if form.non_field_errors %}
                <div class="login-form-action clearfix">
                <div class="alert alert-error alert-dismissible fade in">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <strong>出错了：</strong> {{ form.non_field_errors.0 }}
                </div>
                </div>
                {% endif %}
            </form>
        </div>
        <div class="login-form-links link1 " data-animation="fadeInLeftBig" data-animation-delay=".2s">
            <h4 class="blue">还没有帐号？</h4>
            <span>别急，</span>
            <a href="{% url 'home:register' %}" class="blue">点这里</a>
            <span>去注册</span>
        </div>
        <div class="login-form-links link2 " data-animation="fadeInRightBig" data-animation-delay=".4s">
            <h4 class="green">忘记密码了？</h4>
            <span>别担心，</span>
            <a href="{% url 'password_reset_recover' %}" class="green">点这里</a>
            <span>找回密码</span>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    <script src="//cdn.bootcss.com/jquery-placeholder/2.3.1/jquery.placeholder.min.js"></script>
    <script src="//cdn.bootcss.com/iCheck/1.0.2/icheck.min.js"></script>
    <script src="//static.geetest.com/static/tools/gt.js"></script>
    <script type="text/javascript">
        var handlerEmbed = function (captchaObj) {
            $("#embed-submit").click(function (e) {
                var validate = captchaObj.getValidate();
                if (!validate) {
                    $("#notice")[0].className = "show";
                    setTimeout(function () {
                        $("#notice")[0].className = "hide";
                    }, 2000);
                    e.preventDefault();
                }
            });
            // 将验证码加到id为captcha的元素里
            captchaObj.appendTo("#embed-captcha");
            captchaObj.onReady(function () {
                $("#wait")[0].className = "hide";
            });
        };
        $.post('{% url 'home:get_gee_captcha' %}?t='+ (new Date()).getTime(),
            {'csrfmiddlewaretoken':'{{ csrf_token }}'},
            function(data){
                initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "float", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
            }, handlerEmbed);
        });
        $(function () {
            $("input").iCheck({
                checkboxClass: 'icheckbox_square-blue',
                increaseArea: '20%' // optional
            });

            $(".form-control").focus(function () {
                $(this).closest(".textbox-wrap").addClass("focused");
            }).blur(function () {
                $(this).closest(".textbox-wrap").removeClass("focused");
            });
        });
    </script>
{% endblock %}

templates/home/register.html
{% extends 'home/layout.html' %}
{% block title %}用户注册{% endblock %}
{% block content %}
<!-- #region Registration Form -->
<div class="eternity-form container">
    <div class="registration-form-section">
        <form method="post">
            <div class="section-title reg-header">
                <h3>注册新账户</h3>
            </div>{% csrf_token %}
            <div class="clearfix">
                <div class="col-sm-6 registration-left-section">
                    <div class="reg-content">
                        <div class="textbox-wrap">
                            <div class="input-group">
                                <span class="input-group-addon "><i class="fa fa-user"></i></span>
                                {{ form.username }}
                            </div>
                            {% if form.username.errors %}<label class="label-warning val-error">{{ form.username.errors.0 }}</label>{% endif %}
                        </div>
                        <div class="textbox-wrap">
                            <div class="input-group">
                                <span class="input-group-addon "><i class="fa fa-key"></i></span>
                                {{ form.password }}
                            </div>
                            {% if form.password.errors %}<label class="label-warning val-error">{{ form.password.errors.0 }}</label>{% endif %}
                        </div>
                        <div class="textbox-wrap">
                            <div class="input-group">
                                <span class="input-group-addon "><i class="fa fa-key"></i></span>
                                {{ form.password2 }}
                            </div>
                            {% if form.password2.errors %}<label class="label-warning val-error">{{ form.password2.errors.0 }}</label>{% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 registration-right-section">
                    <div class="reg-content">
                        <div class="textbox-wrap">
                            <div class="input-group">
                                <span class="input-group-addon "><i class="fa fa-envelope-o"></i></span>
                                {{ form.email }}
                            </div>
                            {% if form.email.errors %}<label class="label-warning val-error">{{ form.email.errors.0 }}</label>{% endif %}
                        </div>
                        <div class="textbox-wrap">
                            <div class="input-group">
                                <span class="input-group-addon "><i class="fa fa-plane"></i></span>
                                {{ form.invite_code }}
                            </div>
                            <a href="{% url 'home:invite_code' %}"><small for="">还没有邀请码？</small></a>
                            {% if form.invite_code.errors %}<label class="label-warning val-error">{{ form.invite_code.errors.0 }}</label>{% endif %}
                        </div>
                        <div style="margin: 12px 0 0 6px">
                           <div id="embed-captcha"></div>
                            <p id="wait" class="show">正在加载验证码......</p>
                            <p id="notice" class="hide">请先拖动验证码到相应位置</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="registration-form-action clearfix">
                <a href="{% url 'home:login' %}" class="btn btn-success pull-left blue-btn ">
                    <i class="fa fa-chevron-left"></i>&nbsp; &nbsp;返回登录
                </a>
                <button type="submit" id="embed-submit" class="btn btn-success pull-right green-btn ">立即注册 &nbsp; <i class="fa fa-chevron-right"></i></button>

            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block js %}
    <script src="//cdn.bootcss.com/jquery-placeholder/2.3.1/jquery.placeholder.min.js"></script>
    <script src="//cdn.bootcss.com/iCheck/1.0.2/icheck.min.js"></script>
    <script src="//static.geetest.com/static/tools/gt.js"></script>
    <script type="text/javascript">
        var handlerEmbed = function (captchaObj) {
            $("#embed-submit").click(function (e) {
                var validate = captchaObj.getValidate();
                if (!validate) {
                    $("#notice")[0].className = "show";
                    setTimeout(function () {
                        $("#notice")[0].className = "hide";
                    }, 2000);
                    e.preventDefault();
                }
            });
            // 将验证码加到id为captcha的元素里
            captchaObj.appendTo("#embed-captcha");
            captchaObj.onReady(function () {
                $("#wait")[0].className = "hide";
            });
        };
        $.post('{% url 'home:get_gee_captcha' %}?t='+ (new Date()).getTime(),
            {'csrfmiddlewaretoken':'{{ csrf_token }}'},
            function(data){
                initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "float", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
            }, handlerEmbed);
        });
        $(function () {
            $("input").iCheck({
                checkboxClass: 'icheckbox_square-blue',
                increaseArea: '20%' // optional
            });

            $(".form-control").focus(function () {
                $(this).closest(".textbox-wrap").addClass("focused");
            }).blur(function () {
                $(this).closest(".textbox-wrap").removeClass("focused");
            });
        });
    </script>
{% endblock %}