api/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
@author: alishtory
@site: https://github.com/alishtory/xsadmin
@time: 2017/3/7 21:37
'''

from .views import *
from django.conf.urls import url,include
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse

@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'user_port': reverse('api:user_port', request=request, format=format),
    })

urlpatterns = [
    url(r'^$', api_root),
    url(r'^user_port/$', UserPortView.as_view(), name='user_port'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += [
    url(r'^wechat/$', WeChatView.as_view(), name='wechat'),
]

home/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
@author: alishtory
@site: https://github.com/alishtory/xsadmin
@time: 2017/2/26 16:57
'''
from django.conf.urls import url
from .views import *

app_name = 'home'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^get_gee_captcha/$', GeeCaptchaView.as_view(), name='get_gee_captcha'),
    url(r'^code\.html$', InviteCodeView.as_view(), name='invite_code'),
    url(r'^(?P<slug>[\w-]+)\.html$', PostPageView.as_view(), name= 'post_page'),
    url(r'^(index/)?$', PostPageView.as_view(), name='index'),
]

user/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
@author: alishtory
@site: https://github.com/alishtory/xsadmin
@time: 2017/2/26 18:23
'''

from django.conf.urls import url
from .views import *
from django.views.generic import TemplateView
from django.urls import reverse_lazy

app_name = 'user'

urlpatterns = [
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^(index/|dashboard/)?$', DashboardView.as_view(),name='dashboard'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^personal_profile/$', PersonalProfileView.as_view(), name='personal_profile'),
    url(r'^passwd/$', PasswdView.as_view(), name='passwd'),
    url(r'^checkin/$', CheckInView.as_view(), name='checkin'),
    url(r'^switch_node_group/$', SwitchNodeGroupView.as_view(), name='switch_node_group'),
    url(r'^password/$', PasswordView.as_view(), name='password'),
    url(r'^nodes/(?P<tag_slug>[\w-]+)?$', NodeListView.as_view(), name='nodes'),
    url(r'^node_qr_info/$', NodeQrInfoView.as_view(), name= 'node_qr_info'),
    url(r'^download_cfg/$', DownloadNodeCfgView.as_view(), name='download_cfg'),
    url(r'^post_detail/(?P<pk>\d+)$', PostDetailView.as_view(), name= 'post_detail'),
    url(r'^posts/$', PostListView.as_view(), name='posts'),
]

menus = (
    {'title': '仪表盘', 'title_en': 'Dashboard', 'icon': 'dashboard', 'url_name': 'user:dashboard', 'children': ()},
    {'title': '用户中心', 'title_en': 'User Center','icon': 'user', 'url_name': '', 'children': (
        {'title': '我的信息', 'title_en': 'My Profile', 'icon': 'users', 'url_name': 'user:profile'},
        {'title': '安全设置', 'title_en': 'Safe Setting', 'icon': 'user-secret', 'url_name': 'user:password'},
        {'title': '连接设置', 'title_en': 'Connection Setting', 'icon': 'connectdevelop', 'url_name': 'user:passwd'},
        {'title': '用户属性', 'title_en': 'Personal Profile', 'icon': 'user-md', 'url_name': 'user:personal_profile'},
    )},
   {'title': '每日签到', 'title_en': 'Check In', 'icon': 'flag-checkered', 'url_name': 'user:checkin', 'children': ()},
    {'title': '节点中心', 'title_en': 'Node Center', 'icon': 'codepen', 'url_name': 'user:nodes', 'children': ()},
    {'title': '站内通告', 'title_en': 'Site Notice', 'icon': 'comment', 'url_name': 'user:posts', 'children': (
        {'title': '通告详情', 'title_en': 'Notice Detail', 'icon': 'comment', 'url_name': 'user:post_detail', 'no_reverse': True},
    )},
)

xsadmin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home.views import MyRecover
from django.views.generic import RedirectView
from django.urls import reverse_lazy
admin.autodiscover()
admin.site.login = RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^user/', include('user.urls',namespace='user')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^pwd/recover/$', MyRecover.as_view(), name='password_reset_recover'),
    url(r'^pwd/', include('password_reset.urls')),
    url(r'', include('home.urls',namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

user/models.py
# -*- coding:utf-8 -*-
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db.models import Max, Count, Q
from . import utils
import random, base64
from django.core import validators
from django.urls import reverse
from django_summernote.models import AbstractAttachment
from django.db.utils import ProgrammingError, InternalError
from django.utils import timezone
from django.conf import settings

def get_usefull_port():
    try:
        max_port = User.objects.aggregate(Max('port')).get('port__max')
    except ProgrammingError:
        max_port = None
    if not max_port:
        max_port = 17236
    new_port = int(max_port) + random.randint(2, 5)
    if new_port in (24554, 60177, 60179):
        new_port += 1
    return new_port

def get_node_group():
    if hasattr(settings, 'NODE_GROUPS') and len(settings.NODE_GROUPS) > 1:
        try:
            group_ids = set()
            for g in settings.NODE_GROUPS:
                group_ids.add(g[0])
            user_group_ids = User.objects.values_list('node_group_id', flat=True).order_by().distinct()
            #print(user_group_ids.query)
            #print(set(user_group_ids))
            not_have_group = group_ids-set(user_group_ids)
            if not_have_group:
                return random.choice(tuple(not_have_group))
            user_count = User.objects.filter(Q(switch=True)&Q(is_active=True)&Q(node_group_id__in=group_ids)).values('node_group_id').annotate(n=Count('*')).order_by('n')
            #print(user_count.query)
            if user_count:
                return user_count[0].get('node_group_id', 1)
        except (ProgrammingError, InternalError):
            pass
    return 1

# 用户模型.
class User(AbstractUser):

    avatar = models.CharField(verbose_name='头像', max_length=63,default='avatar1.png')
    port = models.PositiveSmallIntegerField(verbose_name='端口',unique=True, default= get_usefull_port)
    passwd = models.CharField(verbose_name='端口密码',max_length=16,default=utils.gen_passwd)
    t = models.IntegerField(verbose_name='最后使用时间戳',default=0)
    u = models.BigIntegerField(verbose_name='上传流量',default=0)
    d = models.BigIntegerField(verbose_name='下载流量',default=0)
    transfer_enable = models.BigIntegerField(verbose_name='每月流量限额',default=settings.INIT_TRANS_ENABLE)
    switch = models.BooleanField(verbose_name='流量开关状态',default=True)
    last_check_in_time = models.DateTimeField(verbose_name='最后签到时间',null=True)
    check_in_count = models.IntegerField(verbose_name='连续签到次数',default=0)

    reg_ip = models.GenericIPAddressField(verbose_name='注册IP',unpack_ipv4=True,null=True)
    last_login_ip = models.GenericIPAddressField(verbose_name='上次登录IP',unpack_ipv4=True,null=True)
    last_login_date = models.DateTimeField(verbose_name='上次登录时间',null=True,auto_now_add=True)
    this_login_ip = models.GenericIPAddressField(verbose_name='本次登录IP',unpack_ipv4=True,null=True)
    this_login_date = models.DateTimeField(verbose_name='本次登录时间',null=True,auto_now_add=True)

    invite_num = models.IntegerField(verbose_name='可以生成邀请码的个数',default=0)
    last_gen_invite_code_time = models.DateTimeField(verbose_name='上次生成邀请码时间',null=True)

    email_validate_code = models.CharField(max_length=63,verbose_name='邮箱验证码',default=utils.gen_val_code)
    bind_email = models.BooleanField(verbose_name='是否已验证邮箱', default=False)

    wx_validate_code = models.CharField(max_length=31,verbose_name='微信公众号验证码',default=utils.gen_val_code)
    wxopenid = models.CharField(max_length=127,verbose_name='微信OPENID',null=True)

    node_group_id = models.PositiveSmallIntegerField('节点组', default=get_node_group, choices=settings.NODE_GROUPS, help_text='settings_custom.py的NODE_GROUPS字段')
    last_change_node_group_time = models.DateTimeField('最后修改节点组时间', null=True, blank=True, default=None)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

#节点模型
class AbstractNode(models.Model):
    METHOD_CHOICES = (
        ('rc4-md5', 'rc4-md5'),
        ('chacha20', 'chacha20'),
        ('aes-256-cfb', 'aes-256-cfb'),
        ('aes-192-cfb', 'aes-192-cfb'),
        ('aes-128-cfb', 'aes-128-cfb'),
        ('salsa20', 'salsa20'),
        ('rc4', 'rc4'),
        ('table', 'table'),
    )

    STATUS_CHOICES = (
        ('ON-LINE','正常'),
        ('OFF-LINE','离线'),
        ('BANDWIDTH-OVER','流量用完'),
        ('ATTACKED','被攻击中'),
        ('INIT','初始化中'),
        ('MAINTAIN','维护中'),
        ('OUT','下线'),
    )
    name = models.CharField(max_length=63,verbose_name='节点名称')
    location = models.CharField(max_length=127, verbose_name='节点地理位置')
    flag = models.CharField(max_length=63, verbose_name='节点国旗图标', blank=True, default=None, help_text='us：美国；jp：日本；hk：香港；sg：新加坡；cn：中国；kr：韩国；gb：英国；参考：http://flag-icon-css.lip.is/')
    ip = models.GenericIPAddressField(verbose_name='节点IP地址',protocol='IPv4')
    ipv6 = models.GenericIPAddressField(blank=True, null= True , protocol='IPv6', verbose_name='节点IPv6地址')
    method = models.CharField(choices=METHOD_CHOICES,max_length=63, default='chacha20', verbose_name='节点加密方式')
    info = models.TextField(max_length=255, verbose_name='节点信息')
    status = models.CharField(max_length=63, choices=STATUS_CHOICES,default='INIT', verbose_name='节点状态')
    traffic_rate = models.PositiveIntegerField(verbose_name='流量倍率百分比',help_text='100表示默认1倍', default=100)
    sort = models.SmallIntegerField(verbose_name='排序', default=0, help_text='小的在前面')
    remark_for_admin = models.TextField('管理员备注',null=True, blank=True, default=None)
    tags = models.ManyToManyField('NodeTag', verbose_name='标签集合', blank=True)

    #SSR属性
    ORIGIN_CHOICES = (
        ('origin','origin：原版协议'),
        ('auth_sha1_v4','auth_sha1_v4：较高安全性，有宽松的时间校对要求，混淆强度大'),
        ('auth_aes128_md5','auth_aes128_md5：最高安全性，有宽松的时间校对要求，计算量相对高一些，混淆强度较大'),
        ('auth_aes128_sha1','auth_aes128_sha1：最高安全性，有宽松的时间校对要求，计算量相对高一些，混淆强度较大'),
        ('auth_sha1_v4_compatible','auth_sha1_v4_compatible，兼容版'),
    )
    protocol = models.CharField(max_length=63,verbose_name='协议插件',default='auth_sha1_v4_compatible',choices=ORIGIN_CHOICES,help_text='协议推荐：协议用auth_aes128_md5或auth_aes128_sha1最佳（但是不支持原版SS协议），此时即使使用rc4加密亦可，混淆随意；_compatible后缀表示兼容原版SS协议')
    protocol_param = models.CharField(max_length=63,verbose_name='协议插件参数',blank=True,default='')
    OBFS_CHOICES = (
        ('plain','plain：不混淆，无参数'),
        ('tls1.2_ticket_auth','tls1.2_ticket_auth：伪装为tls请求。参数配置与http_simple一样'),
        ('http_simple','http_simple：简易伪装为http get请求'),
        ('http_post','http_post：与http_simple绝大部分相同，POST伪装方式'),
        ('tls1.2_ticket_auth_compatible','tls1.2_ticket_auth_compatible：兼容版'),
        ('http_simple_compatible','http_simple_compatible：兼容版'),
        ('http_post_compatible','http_post_compatible：兼容版'),
    )
    obfs = models.CharField(max_length=127,verbose_name='混淆插件',choices=OBFS_CHOICES,default='tls1.2_ticket_auth_compatible',
                            help_text='混淆推荐：如果QoS在你的地区明显，混淆建议在http_simple与tls1.2_ticket_auth中选择，具体选择可以通过自己的试验得出。如果选择混淆后反而变慢，那么混淆请选择plain。如果你不在乎QoS，但担心你的个人vps能不能持久使用，那么混淆选择plain或tls1.2_ticket_auth，协议选择auth_aes128_md5或auth_aes128_sha1')
    obfs_param = models.CharField(max_length=63,verbose_name='混淆插件参数',blank=True,default='')

    ssh_port = models.PositiveSmallIntegerField(verbose_name='SSH端口号',help_text='用于发送远程命令',default=22)
    last_api_request_time = models.DateTimeField(auto_now_add=True, verbose_name='最后调用远程API的时间')

    slug = models.CharField(verbose_name='API Key',unique=True, db_index=True, max_length=127, default=utils.gen_api_key, editable=False)
    api_key = models.CharField(verbose_name='API Key',unique=True,max_length=127,default=utils.gen_api_key, editable=False)
    api_secret = models.CharField(max_length=255,verbose_name='API Secret 密匙',default=utils.gen_api_secret)

    class Meta:
        abstract = True

    def __str__(self):
        return '%s[%s]'%(self.name,self.ip)


    passwd = ''
    port = ''

    @property
    def ss_url(self):
        return 'ss://%s' % (self.ss_protocol,)

    @property
    def ss_qrcode(self):
        return 'ss://%s' % (base64.encodebytes(self.ss_protocol.encode()).decode().strip(),)

    @property
    def ss_protocol(self):
        return '%s:%s@%s:%s' % (self.method, self.passwd, self.ip, self.port)

class Node(AbstractNode):
    node_group_id = models.PositiveSmallIntegerField('节点组', default=1, choices=settings.NODE_GROUPS,
                                                     help_text='settings_custom.py的NODE_GROUPS字段')
    class Meta:
        verbose_name = '节点'
        verbose_name_plural = verbose_name
        ordering = ['sort', 'id']

#节点标签模型
class NodeTag(models.Model):

    slug = models.CharField(max_length=63,verbose_name='标识', help_text='请使用字母、数字、下划线、中划线组成，不可重复', primary_key=True,
                validators= (validators.RegexValidator(r'[\w-]+'),), unique=True,)
    name = models.CharField(max_length=63, verbose_name='标签名称')

    class Meta:
        verbose_name = '节点标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s:%s' % (self.slug, self.name)

#邀请码模型
class InviteCode(models.Model):

    code = models.CharField(max_length=127,verbose_name='邀请码',default=utils.gen_invite_code,unique=True)
    create_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    used_time = models.DateTimeField(null=True, blank=True, verbose_name='使用时间')
    TYPE_DEFAULT = 'DEFAULT'
    TYPE_TIMING = 'TIMING'
    TYPE_USERS = 'USERS'
    TCHOICES = (
        (TYPE_DEFAULT,'默认类型'),
        (TYPE_TIMING,'定时发放类型'),
        (TYPE_USERS,'用户生成类型'),
    )
    type = models.CharField(max_length=15,verbose_name='邀请码类型',default=TYPE_DEFAULT,choices=TCHOICES)
    show_time = models.DateTimeField(null=True, blank=True, verbose_name='公开显示时间')

templates/user/breadcrumb.html
<div class='col-xs-12'>
    <div class="page-title">
        <div class="pull-left"><!-- PAGE HEADING TAG - START -->
            <h1 class="title">{{ USER_BREADCRUMBS_TITLE|default:'无标题' }}</h1><!-- PAGE HEADING TAG - END -->
        </div>
        <div class="pull-right hidden-xs">
            <ol class="breadcrumb">
                {% for bread in USER_BREADCRUMBS %}
                    <li>
                        <a href="{% if not bread.no_reverse and bread.url_name %}{% url bread.url_name %}{% else %}javascript:void(0){% endif %}">
                            {% if forloop.first %}<i class="fa fa-{{ bread.icon }}"></i>{% endif %} {{ bread.title }}
                        </a>
                    </li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
<div class="clearfix"></div>

templates/user/footer.html
<footer id="main-footer">
	<div class="pull-right hidden-xs">
		<b>Version</b> {{ PROJECT_VERSION }}</div>
	<strong>Copyright © 2016-{% now 'Y' %} Powered by <a href="{{ PROJECT_URL }}" target="_blank">{{ PROJECT_NAME }}</a>.
	</strong> All rights reserved.
</footer>

templates/user/nodes.html
{% extends './layout.html' %}{% load static %}
{% block content %}
<section class="box">
    <header class="panel_header">
        <h2 class="title pull-left"><a href="{% url 'user:nodes' %}">节点列表</a>
            {% if node_tag %}　<small>标签含：<a href="{% url 'user:nodes' node_tag.slug %}">{{ node_tag.name }}</a></small>{% endif %}
        </h2>
    <div class="action title pull-right" style="font-size: 13px;margin-right: 30px">
        <a href="{% url 'user:download_cfg' %}"><i class="fa fa-download"></i> 配置文件</a>
    </div>
    </header>
<div class="content-body">
    <div class="row">
        <div class="col-xs-12 tab-content node-lists">
        <div role="tabpanel" class="clearfix">
        <ul class="nav nav-tabs transparent">
        {% for ng in NODE_GROUPS %}
        <li class="{% if ng.0 == user.node_group_id %}active{% endif %}">
            <a href="#node-tab{{ ng.0 }}" data-toggle="tab">{{ ng.1 }}</a>
        </li>
        {% endfor %}
        </ul>
        <div class="tab-content transparent">
        {% for ng in NODE_GROUPS %}
        {% if ng.0 == user.node_group_id %}
            <div class="tab-pane fade active in" id="node-tab{{ ng.0 }}">
                {% for node in nodeLists %}
            <div class="job-ad-item">
                <div class="item-info">
                    <div class="item-image-box">
                        <div class="item-image">
                        <a href="javascript:void(0)">
                            {% if node.flag %}
                                <span class="flag-icon flag-icon-{{ node.flag }}"></span>
                            {% else %}
                                <img src="{% static 'images/logo.png' %}" alt="Image" class="img-responsive">
                            {% endif %}
                            </a>
                        </div><!-- item-image -->
                    </div>

                    <div class="ad-info">
                        <div class="node-title">{{ node.name }}</div>
                        <div class="node-info">{{ node.info }}</div>
                        <div class="ad-meta">
                            <ul>
                                <li><i class="fa fa-map-marker" aria-hidden="true"></i>{{ node.location }}</li>
                                <li><i class="fa fa-get-pocket" aria-hidden="true"></i><code>{{ node.method }}</code></li>
                                <li><i class="fa fa-heartbeat" aria-hidden="true"></i>{{ node.get_status_display }}</li>
                                {% for tag in node.tags.all %}{% if forloop.first %}<li><i class="fa fa-tags" aria-hidden="true"></i> {% endif %}<a href="{% url 'user:nodes' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}、{% endif %}{% endfor %}</li>
                            </ul>
                        </div><!-- ad-meta -->
                    </div><!-- ad-info -->
                    <div class="button">
                        <a href="javascript:showQrCode('{{ node.slug }}')"><i class="fa fa-qrcode icon-xs icon-accent animated bounceIn"></i> 节点连接信息</a>　
                        {# <a href="javascript:void(0)"><i class="fa fa-cloud icon-xs icon-success animated rotateIn"></i> 详细信息</a>  #}
                    </div>
                </div><!-- item-info -->
            </div><!-- ad-item -->
            {% endfor %}
            </div>
        {% else %}
            <div class="tab-pane fade in" id="node-tab{{ ng.0 }}">
            <div class="node-group-none">
                <h4 class="title">很抱歉，您暂时未开通此节点组</h4>
                <p>用户每72小时可以进行一次节点组切换</p>
                {% if node_group_switchable %}
                    <p><a href="javascript:switch_node_group({{ ng.0 }})" class="btn btn-primary">切换为本节点组</a></p>
                {% else %}
                <div class="node-getting-started"></div>
                <p class="node-getting-started-note"></p>
                {% endif %}
            </div>
            </div>
        {% endif %}
        {% endfor %}
        </div>
        </div>
        </div>
    </div>
</div>
</section>
<!-- modal start -->
<div class="modal fade col-xs-12" id="cmpltadminModal-qrcode" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">节点连接信息</h4>
            </div>
            <div class="modal-body">
                <div class="loader">
                    <div class="ball-pulse-sync"><div></div><div></div><div></div></div>
                    <p>加载中，客观请稍等...</p>
                </div>
                <div class="row" id="qrcode-ajax-content">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade col-xs-12" id="switch-node-group" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">切换节点组</h4>
            </div>
            <div class="modal-body">
                <p>请注意：</p>
                <ol>
                    <li>节点组切换后，您可能需要稍等几分钟，新节点才会生效，您会得到新的节点，也需要重新配置各个节点。</li>
                    <li>用户每72小时才能切换一次节点组，请确定后再进行节点切换</li>
                    <li>请勿随意反复做切换操作</li>
                </ol>
                <p>
                <form method="post" action="{% url 'user:switch_node_group' %}">
                {% csrf_token %}
                    <input type="hidden" name="node_group_id" id="node_group_id-input">
                <div style="margin-bottom: 30px;">
                   <div id="embed-captcha"></div>
                    <p id="wait" class="show">正在加载验证码......</p>
                    <p id="notice" class="hide">请先拖动验证码到相应位置</p>
                </div>
                <button type="submit" id="embed-submit" class="btn btn-success green-btn"> 切换
                    <i class="fa fa-check-circle"></i></button>
                </form>
                </p>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block js %}
    <script src="//cdn.bootcss.com/jquery.qrcode/1.0/jquery.qrcode.min.js"></script>
    <script src="//static.geetest.com/static/tools/gt.js"></script>
    <script type="text/javascript">
        function showQrCode(slug) {
            $('#cmpltadminModal-qrcode .loader').show();
            $("#qrcode-ajax-content").html('');
            $('#cmpltadminModal-qrcode').modal('show',{backdrop:"static"});
            $.post('{% url "user:node_qr_info" %}',{'csrfmiddlewaretoken':'{{ csrf_token }}','slug':slug},function(data){
                $('#cmpltadminModal-qrcode .loader').hide();
                $("#qrcode-ajax-content").html(data);
            },'html');
        }
        function switch_node_group(id) {
            $("#node_group_id-input").val(id);
            $("#switch-node-group").modal('show',{backdrop:"static"});
        }

        var note = $('.node-getting-started-note'),
		ts = new Date('{{ node_group_switchable_time|date:"m d,Y H:i:s" }}');
        $('.node-getting-started').each(function () {
            $(this).countdown({
            timestamp	: ts,
            callback	: function(days, hours, minutes, seconds){
                var message = "还需要等 ";
                message += days + "天";
                message += hours + "小时";
                message += minutes + "分钟";
                message += seconds + "秒，您才可以切换";
                note.html(message);
            }
        });
        });
        //geetest
        var handlerEmbed = function (captchaObj) {
            $("#embed-submit").click(function (e) {
                var validate = captchaObj.getValidate();
                if (!validate) {
                    $("#notice")[0].className = "show";
                    setTimeout(function () {
                        $("#notice")[0].className = "hide";
                    }, 2000);
                    e.preventDefault();
                }
            });
            // 将验证码加到id为captcha的元素里
            captchaObj.appendTo("#embed-captcha");
            captchaObj.onReady(function () {
                $("#wait")[0].className = "hide";
            });
        };
        $.post('{% url 'home:get_gee_captcha' %}?t='+ (new Date()).getTime(),
            {'csrfmiddlewaretoken':'{{ csrf_token }}'},
            function(data){
                initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "embed", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
            }, handlerEmbed);
        });
</script>
    </script>
{% endblock %}

templates/user/topbar.html
<!-- START TOPBAR -->{% load static %}
<div class='page-topbar '>
    <div class='logo-area'>
        <a href="{% url 'home:index' %}"><img  class="logo-img" src="{% static 'images/logo.png' %}"></a>
        <span class="logo-title"><span>{{ SITE_NAME }}</span></span>
    </div>
    <div class='quick-area'>
        <div class='pull-left'>
            <ul class="info-menu left-links list-inline list-unstyled">
                <li class="sidebar-toggle-wrap">
                    <a href="javascript:void(0);" data-toggle="sidebar" class="sidebar_toggle">
                        <i class="fa fa-bars"></i>
                    </a>
                </li>
                </li>
            </ul>
        </div>
        <div class='pull-right'>
            <ul class="info-menu right-links list-inline list-unstyled">
                {% if user.is_staff %}
                <li class="admin-menu">
                    <a class='' href="{% url 'admin:index' %}" target="_blank">后台管理</a>
                </li>
                {% endif %}
                <li class="profile">
                    <a href="javascript:void(0)" data-toggle="dropdown" class="toggle">
                        <img src="{% static 'images/avatars/' %}{{ user.avatar }}" alt="user-image" class="img-circle img-inline">
                        <span>{{ user.get_full_name|default:user.username }} <i class="fa fa-angle-down"></i></span>
                    </a>
                    <ul class="dropdown-menu profile animated fadeIn">
                        <li>
                            <a href="{% url 'user:profile' %}">
                                <i class="fa fa-wrench"></i>
                                设置
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'user:profile' %}">
                                <i class="fa fa-user"></i>
                                我的信息
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'user:profile' %}">
                                <i class="fa fa-info"></i>&nbsp; 帮助
                            </a>
                        </li>
                        <li class="last">
                            <a href="{% url 'user:logout' %}">
                                <i class="fa fa-lock"></i>
                                退出
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

</div>
<!-- END TOPBAR -->